services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/Aman42823/metabase.git # optional
    plan: starter # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: elephant
          property: connectionString
databases:
  - name: elephant
    databaseName: orders_t7np
    ipAllowList: [] # only allow internal connections
